# Generated by Django 6.0.6 on 2026-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user', models.CharField(db_column='sourceUser')),
                ('target_user', models.CharField(db_column='targetUser')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, db_column='createdDateTime')),
                ('updated_date_time', models.DateTimeField(auto_now=True, db_column='updatedDateTime')),
            ],
        ),
    ]
